### ISSUE TITLE
The Office365 application cannot be installed with OpenID Connect version > 2.0.0

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-office365#25]
This issue was reported by a support client. When trying to install the extension, the client gets the following error : 

![image](https://github.com/xwikisas/application-office365/assets/5938943/9fc61089-307e-47cf-acf2-af09058d887d)

**Comment by aubincleme** [comment]
Closing as it turns out that the installation works well on a vanilla version of XWiki 14.10.13. The extension `net.minidev:json-smart` may be already installed by another dependency.

**Comment by aubincleme** [comment]
Re-opening the issue as I have found the root cause : it turns out that this extension cannot be installed with the OpenID Connect Authenticator v2.0.1. As the authenticator is fairly used today, it could be useful to try to find a solution.

**Comment by oanalavinia** [comment]
Not an easy fix unfortunately
[This](https://github.com/AzureAD/azure-activedirectory-library-for-java) dependency (microsoft azure java library) brings a [transitive dependency](https://mvnrepository.com/artifact/net.minidev/json-smart) with a fixed version range `[1.3.3,2.4.7]`. But OIDC has the version `2.4.11` defined since the [last upgrade](https://github.com/xwiki-contrib/oidc/commit/f7dbc854999664d102c4bb0e5015a061431444df) (it was upgraded to use 14.10 as the minimal parent)
The problem is that this ADAL library was archived this month and we already have the last version. So we have to migrate to [MSAL4J](https://learn.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java) in order to fix the problem. (upgrade + moving code from groovy, refactoring probably)
A quick fix for now should be to use a lower OIDC version ( \<= 1.37.4 )
